### ISSUE TITLE
potential use

### ISSUE THREAD

**Issue by iferencik** [cogeotiff/rio-tiler-mvt#5]
@vincentsarago,

I'd like to know if it would be possible to use [rio-tiler-mvt](https://github.com/cogeotiff/rio-tiler-mvt) to extract individual pixels from a geotiff/numpy array and serve them further as MVT points.

I have a high res (30) raster dataset and would be curios if this could work .

thanks in advance

**Comment by vincentsarago** [comment]
@iferencik that's absolutely the use case of rio-tiler-mvt 

you can try with https://github.com/developmentseed/rio-viz (If you do `pip install rio-viz["mvt"]`) 

https://github.com/developmentseed/rio-viz#3d-experimental
